resources:
  - ../base

configMapGenerator:
  - name: gateway-config
    envs:
      - .env.gateway

secretGenerator:
  - name: messenger-credentials
    envs:
      - .env.messenger.secrets

  - name: database-credentials
    envs:
      - .env.database.secrets
